whenever sqlerror exit;
ALTER SESSION SET CURRENT_SCHEMA = CDM;

create or replace PACKAGE         ARCHIVE_PARTITION AS 

PROCEDURE ARCH_PARTITION (
    TABLE_NAME IN VARCHAR2 
    , NUM_MONTHS IN NUMBER DEFAULT 3 
    , ARCH_SUFFIX IN varchar2 DEFAULT '_HIST' 
    , DER_TABLE IN varchar2 DEFAULT '' 
    , DER_TABLE_KEY IN varchar2 DEFAULT '' 
    );  
    
PROCEDURE DROP_IF_EXIST (
    TABLE_NAME IN VARCHAR2
    );

END ARCHIVE_PARTITION;