whenever sqlerror exit;
ALTER SESSION SET CURRENT_SCHEMA = CDM;

--------------------------------------------------------
--  DDL for Table RTDM_CLIENT_APPLICATION_ARCH
--------------------------------------------------------

CREATE TABLE CDM.RTDM_CLIENT_APPLICATION_ARCH
   (	"APPLICATION_ID" NUMBER, 
	"CLIENT_CD" NUMBER, 
	"INTERACTION_ID" VARCHAR2(30 BYTE), 
	"DECISION_DTTM" TIMESTAMP (6), 
	"DECISION_ID" NUMBER, 
	"REQUEST_DTTM" TIMESTAMP (6), 
	"INT_STATUS" VARCHAR2(1000 CHAR), 
	"SEGMENT_CD" VARCHAR2(30 BYTE), 
	 RTDM_QUERY_XML_PRODUCT2CODE VARCHAR2(36 BYTE), 
     RTDM_QUERY_XML_CHANNEL  VARCHAR2(36 BYTE),
	"REQUESTED_LIMIT" NUMBER, 
	"REQUESTED_TERM" NUMBER, 
	"RTDM_RESPONSE_XML" VARCHAR2(36 CHAR), 
	"CAMPAIGN_CD" VARCHAR2(30 BYTE), 
	"REQUEST_ID" VARCHAR2(30 BYTE) DEFAULT CAST('0' as VARCHAR2(30))
   ) SEGMENT CREATION IMMEDIATE 
   COMPRESS BASIC LOGGING
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARTITION BY RANGE ("REQUEST_DTTM") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "BEFORE_1900"  VALUES LESS THAN (TO_DATE(' 1900-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED) 
 ;
 
 alter table RTDM_CLIENT_APPLICATION RENAME TO RTDM_CLIENT_APPLICATION_BKP;
 
--------------------------------------------------------
--  DDL for Table RTDM_CLIENT_APPLICATION
--------------------------------------------------------
 
CREATE TABLE CDM.RTDM_CLIENT_APPLICATION
   (	"APPLICATION_ID" NUMBER, 
	"CLIENT_CD" NUMBER, 
	"DECISION_DTTM" TIMESTAMP (6), 
	"DECISION_ID" NUMBER, 
	"REQUEST_DTTM" TIMESTAMP (6), 
	"INT_STATUS" VARCHAR2(1000 CHAR), 
	"SEGMENT_CD" VARCHAR2(30 BYTE), 
	"RTDM_QUERY_XML" CLOB, 
	"REQUESTED_LIMIT" NUMBER, 
	"REQUESTED_TERM" NUMBER, 
	"RTDM_RESPONSE_XML" CLOB, 
	"CAMPAIGN_CD" VARCHAR2(30 BYTE), 
	"INTERACTION_ID" VARCHAR2(50 BYTE), 
	"REQUEST_ID" VARCHAR2(30 BYTE) DEFAULT CAST('0' as VARCHAR2(30))
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("RTDM_QUERY_XML") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RTDM_RESPONSE_XML") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
 
  PARTITION BY RANGE ("REQUEST_DTTM") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "BEFORE_1900"  VALUES LESS THAN (TO_DATE(' 1900-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED) 
 ;
 



--------------------------------------------------------
--  GRANT
--------------------------------------------------------  
grant EXECUTE, DEBUG on "CDM"."ARCHIVE_PARTITION" to "MA_USER";
grant select,insert on  CDM.RTDM_CLIENT_APPLICATION to MA_USER  with grant option;
grant  delete,update on  CDM.RTDM_CLIENT_APPLICATION to MA_USER;

grant select,insert on  CDM.RTDM_CLIENT_APPLICATION_ARCH to MA_USER  with grant option;
grant  delete,update on  CDM.RTDM_CLIENT_APPLICATION_ARCH to MA_USER;

grant select, delete, insert, update on  CDM.RTDM_CLIENT_APPLICATION to RTDM;

grant select on CDM.RTDM_CLIENT_APPLICATION to CMDM with grant option;
grant select on CDM.RTDM_CLIENT_APPLICATION to U_CRM;
grant select on CDM.RTDM_CLIENT_APPLICATION to CDM_READ_ALL;
  




 
 