--------------------------------------------------------
--  DDL for Index RTDM_CLIENT_DTTM
--------------------------------------------------------
  CREATE INDEX "CDM"."RTDM_CLIENT_DTTM_IX" ON "CDM"."RTDM_CLIENT_APPLICATION" ("REQUEST_DTTM", "CAMPAIGN_CD", "DECISION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IND_RTDM_CL_APP_CLI_CD
--------------------------------------------------------

  CREATE INDEX "CDM"."RCA_CLI_CD_IX" ON "CDM"."RTDM_CLIENT_APPLICATION" ("CLIENT_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDX_RCA_APP_ID
--------------------------------------------------------

  CREATE INDEX "CDM"."RCA_APP_ID_IX" ON "CDM"."RTDM_CLIENT_APPLICATION" ("APPLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RTDM_CL_APPL_CAMPAIGN_CD
--------------------------------------------------------

  CREATE INDEX "CDM"."RCA_CAMPAIGN_CD_IX" ON "CDM"."RTDM_CLIENT_APPLICATION" ("CAMPAIGN_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RTDM_CLIENT_APPLICATION
--------------------------------------------------------

ALTER TABLE "CDM"."RTDM_CLIENT_APPLICATION" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);