whenever sqlerror exit;
ALTER SESSION SET CURRENT_SCHEMA = CDM;


alter table RTDM_CLIENT_APPLICATION RENAME TO RTDM_CLIENT_APPLICATION_OLD;

--------------------------------------------------------
--  DDL for Table RTDM_CLIENT_APPLICATION
--------------------------------------------------------

  CREATE TABLE "CDM"."RTDM_CLIENT_APPLICATION" 
   (	"APPLICATION_ID" NUMBER, 
	"CLIENT_CD" NUMBER, 
	"DECISION_DTTM" TIMESTAMP (6), 
	"DECISION_ID" NUMBER, 
	"REQUEST_DTTM" TIMESTAMP (6), 
	"INT_STATUS" VARCHAR2(1000 CHAR), 
	"SEGMENT_CD" VARCHAR2(30 BYTE), 
	"RTDM_QUERY_XML" CLOB, 
	"REQUESTED_LIMIT" NUMBER, 
	"REQUESTED_TERM" NUMBER, 
	"RTDM_RESPONSE_XML" CLOB, 
	"CAMPAIGN_CD" VARCHAR2(30 BYTE), 
	"INTERACTION_ID" VARCHAR2(50 BYTE), 
	"REQUEST_ID" VARCHAR2(30 BYTE) DEFAULT CAST('0' as VARCHAR2(30))
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("RTDM_QUERY_XML") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RTDM_RESPONSE_XML") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
 insert /*+ APPEND */ into CDM.RTDM_CLIENT_APPLICATION (
 select * from CDM.RTDM_CLIENT_APPLICATION_OLD 
 where  REQUEST_DTTM >= TO_DATE('2017-02-01 00:00:00','SYYYY-MM-DD HH24:MI:SS') 
 );
 commit;
  
--------------------------------------------------------
--  DDL for Index RTDM_CLIENT_DTTM
--------------------------------------------------------

  CREATE INDEX "CDM"."RTDM_CLIENT_DTTM" ON "CDM"."RTDM_CLIENT_APPLICATION" ("REQUEST_DTTM", "CAMPAIGN_CD", "DECISION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IND_RTDM_CL_APP_CLI_CD
--------------------------------------------------------

  CREATE INDEX "CDM"."IND_RTDM_CL_APP_CLI_CD" ON "CDM"."RTDM_CLIENT_APPLICATION" ("CLIENT_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDX_RCA_APP_ID
--------------------------------------------------------

  CREATE INDEX "CDM"."INDX_RCA_APP_ID" ON "CDM"."RTDM_CLIENT_APPLICATION" ("APPLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RTDM_CL_APPL_CAMPAIGN_CD
--------------------------------------------------------

  CREATE INDEX "CDM"."RTDM_CL_APPL_CAMPAIGN_CD" ON "CDM"."RTDM_CLIENT_APPLICATION" ("CAMPAIGN_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RTDM_CLIENT_APPLICATION
--------------------------------------------------------

  ALTER TABLE "CDM"."RTDM_CLIENT_APPLICATION" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  
  DROP TABLE CDM.RTDM_CLIENT_APPLICATION_OLD PURGE;

  EXEC DBMS_STATS.gather_table_stats('CDM', 'RTDM_CLIENT_APPLICATION');

  
  

 
